cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart_summary, name="cart_summary"),
	path('add/', views.cart_add, name="cart_add"),
	path('delete/', views.cart_delete, name="cart_delete"),
	path('update/', views.cart_update, name="cart_update"),
]

inventory/urls.py
from django.urls import path
from .views import inventory_home, product_search, product_page, add_item,  api_get_variants
from . import views

app_name = 'inventory'

urlpatterns = [
    path('', inventory_home, name='inventory_home'),  # Default inventory route
    path('<int:product_id>/', views.product_page, name='product_page'),
    path('add-item/', add_item, name='add_item'),
    path('api/variants/<int:product_id>/', api_get_variants, name='api_get_variants'),
    path('search/', views.product_search, name='inventory'),
    path('order/', views.order_page, name='order'),
]

sales/urls.py
from django.urls import path
from .views import new_sale
from . import views

app_name = 'sales'  # Make sure this matches the app's namespace if it's not global

urlpatterns = [
    path('new/', new_sale, name='new_sale'),
    path('search/', views.search_view, name='search'),  # Ensure you have this
]

sparrow/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('store.urls')),
    path('inventory/', include('inventory.urls'), name='inventory'),
    path('sales/', include('sales.urls'), name='sales'),
    path('cart/', include('cart.urls'), name='cart'),
]

templates/about.html
{% extends 'base.html' %}
{% block content %}

<!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">McSporties...</h1>
                    <p class="lead fw-normal text-white-50 mb-0">We Don't Got It, You Don't Want It.</p>
                </div>
            </div>
        </header>

        <div class="container">
        	<div class="row">
        		<center>
        			<div class="col-8">
        				<br/><br/>
<p align="justify">
One of the last rock n roll Ski Shops. 
<br/><br/>
Est. 1994
<br/><br/>
<br/>3180 Creekside way
<br/>Sun Peaks, BC
<br/>V0E 5N0<br/>
<br/><br/>
                        <br/>
                    <br/>
        			</div>
        		</center>
        	</div>
        </div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Sparrow</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
        
    </head>
    <body>
        {% include 'navbar.html' %}
        {% if messages %}
            {% for message in messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  {{ message }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
            {% endfor %}
        {% endif %}
        
        {% block content %}
        {% endblock %}      
        
    
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; mcsparrow.ca 2024</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

<!-- Header -->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">McSparrow</h1>
            <p class="lead fw-normal text-white-50 mb-0">Look Good, Feel Good, Ski Good.</p>
        </div>
    </div>
</header>

<!-- Section -->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            
            {% for product in products %}
                <div class="col mb-5">
                    <div class="card h-100">


                        <!-- Product details -->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name -->
                                <h5 class="fw-bolder">{{ product.name }}</h5>

                                <!-- Price -->
                                <p>${{ product.price }}</p>
                            </div>
                        </div>

                        <!-- Product actions -->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center">
                                <a class="btn btn-outline-dark mt-auto" href="{% url 'product' product.id %}">View Product</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            
        </div>
    </div>
</section>

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block content %}

<!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Login</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Log In...</p>
                </div>
            </div>
        </header>

        <div class="container">
        	<div class="row">
        		<center>
        			<div class="col-8">

        				<br/><br/>
<form method="POST" action="{% url 'login' %}">
    {% csrf_token %}
    
  <div class="mb-3">
    
    <input type="text" class="form-control" name="username" placeholder="Enter Your Username">
    
  </div>
  <div class="mb-3">
    
    <input type="password" class="form-control" name="password" placeholder="Enter Your Password">
  </div>
  <br/><br/>
  <button type="submit" class="btn btn-secondary">Login</button>
</form>

<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
        			</div>
        		</center>
        	</div>
        </div>

{% endblock %}

templates/navbar.html
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'home' %}">Sparrow</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
            {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'update_user' %}">{{ user.username }}</a></li>
            <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'sales:search' %}">New Sale</a></li>
            <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'inventory:inventory_home' %}">Inventory</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">McSporties</a></li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Profile</a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'update_user' %}">User Profile</a></li>
            <li><hr class="dropdown-divider" /></li>
            <li><a class="dropdown-item" href="{% url 'update_info'  %}">User Info</a></li>
        </ul>
    </li>
    {% if user.is_superuser %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Orders</a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

        </ul>
    </li>
    {% endif %}
    <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
    {% else %}
    <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Register</a></li>
    {% endif %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="">All Products</a></li>
            <li><hr class="dropdown-divider" /></li>
            {% for category in categories %}
            <li><a class="dropdown-item" href="{% url 'category' category %}">{{ category }}
                {% endfor %}
            </ul>
        </li>
    </ul>
    <form class="d-flex">
        <a href="{% url 'cart_summary' %}" class="btn btn-outline-dark"><i class="bi-cart-fill me-1"></i>
            Cart
            <span class="badge bg-dark text-white ms-1 rounded-pill" >

            </span></a>
        </form>
    </div>
</div>
</nav>

templates/register.html
{% extends 'base.html' %}
{% block content %}

<!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Register</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Register for a User Account...</p>
                </div>
            </div>
        </header>

        <div class="container">
        	<div class="row">
        		
        			<div class="col-md-6 offset-md-3">

        				<br/><br/>
<form method="POST" action="{% url 'register' %}">
    {% csrf_token %}
    
    {{ form.as_p }}
    <br/><br/>
    <button type="submit" class="btn btn-secondary">
      Register
    </button>
  
</form>

<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
        			</div>
        		
        	</div>
        </div>

{% endblock %}

templates/update_info.html
{% extends 'base.html' %}
{% block content %}

<!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Update Info</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Update User Info...</p>
                </div>
            </div>
        </header>

        <div class="container">
        	<div class="row">
        		
        			<div class="col-md-6 offset-md-3">

        				<br/><br/>
                    <strong>Billing Information</strong>
                    <br/><br/>
<form method="POST" action="{% url 'update_info' %}">
    {% csrf_token %}
    
    {{ form.as_p }}
    <br/><br/>
    <strong>Shipping Information</strong>
    <br/><br/>
    
    {{ shipping_form.as_p }}


    <br/><br/>
    <button type="submit" class="btn btn-secondary">
      Update Profile
    </button>
</form>

<br/><br/>


<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
        			</div>
        		
        	</div>
        </div>

{% endblock %}

templates/update_password.html
{% extends 'base.html' %}
{% block content %}

<!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Update Password</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Update User Password...</p>
                </div>
            </div>
        </header>

        <div class="container">
        	<div class="row">
        		
        			<div class="col-md-6 offset-md-3">

        				<br/><br/>
<form method="POST" action="{% url 'update_password' %}">
    {% csrf_token %}
    
    {{ form.as_p }}
    <br/><br/>
    <button type="submit" class="btn btn-secondary">
      Update Password
    </button>
  
</form>

<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
        			</div>
        		
        	</div>
        </div>

{% endblock %}

templates/update_user.html
{% extends 'base.html' %}
{% block content %}

<!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Update Profile</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Update User Profile...</p>
                </div>
            </div>
        </header>

        <div class="container">
        	<div class="row">
        		
        			<div class="col-md-6 offset-md-3">

        				<br/><br/>
<form method="POST" action="{% url 'update_user' %}">
    {% csrf_token %}
    
    {{ user_form.as_p }}
    <br/><br/>
    <button type="submit" class="btn btn-secondary">
      Update Profile
    </button>
</form>

<br/><br/>
<a href="{% url 'update_password' %}" class="btn btn-secondary">Update Password</a>

<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
        			</div>
        		
        	</div>
        </div>

{% endblock %}